### PR TITLE
Modified terminology for inclusive language

### PR DESCRIPTION
**Pull request by cognitivegears**
Small change to make language more inclusive.

### CODE REVIEW

**Comment by jmonroe** [comment]
Dummies Approved

**Comment by Groovy-13** [comment]
i hate to break it to you but... there's nothing wrong with the word "dummy" :3
https://dictionary.cambridge.org/dictionary/english/dummy

**Comment by ItsNewe** [comment]
notabug wontfix

**Comment by JackRedstonia** [comment]
NOTABUG WONTFIX

**Comment by reinaldoacosta** [comment]
what a dummy

**Comment by erir910** [comment]
Keep your woke cult out of software development.

**Comment by yourikoeman** [comment]
> is dummy
> sees word "dummy"
> "this offends me"

**Pull request closed without merging**
